### ISSUE TITLE
`asv dev` fails to find executable

### ISSUE THREAD

**Issue by qwhelan** [spacetelescope/asv#197]
As mentioned in #194, when running ```asv dev```, I get the following error:
```
$ asv dev
· No executable found for python same
· Creating environments
· Installing dependencies
· No environments selected
```

The root cause is an inconsistency in how ```Environment``` and its subclasses define the ```python``` argument. ```ExistingEnvironment``` expects ```python``` to be a full name (such as ```python2.7```) while ```VirtualEnv``` and ```Conda``` expect ```python``` to be just a version number (specifically in ```get_environments()``` and ```matches()```). These latter two classes also do not handle the ```python='same'``` special case. This leads to a ```util.which('pythonsame')``` call which fails and returns no environment matches.

I didn't submit a patch as it's unclear what the preferred fix is - ```same``` could be handled individually in each of the plugins (hacky but possibly easier) or it could be replaced with ```None``` inside ```environment.py``` and each subclass would just have to handle the no-version-number case.

**Comment by mdboom** [comment]
I think the issue is the mismatch between the old way (which was to auto-choose an environment) and the new explicit `environment_type` key in `asv.conf.json`.  Do you have an `environment_type` entry?  If so, a workaround may be to remove that for now.  I'll have to fix this up so `dev` continues to work with it again.

**Comment by mdboom** [comment]
@qwhelan: Would you mind testing #198?
