### ISSUE TITLE
Add per-class setup / teardown

### ISSUE THREAD

**Issue by pitrou** [spacetelescope/asv#274]
Similarly to what modern unittest offers, it would be nice to have per-class setup and teardown functions, to set up class-wide resources (such as data samples, etc.)

(see https://docs.python.org/3/library/unittest.html#unittest.TestCase.setUpClass)

**Comment by pv** [comment]
This seems to conflict with the philosophy of running each benchmark in
a separate process.

**Comment by pv** [comment]
I haven't decided if the current behavior is the best way to do this, though; while the benchmark runner needs to be isolated, it's not that clear all benchmarks need to be isolated from each other. It is probably necessary for peak RSS measurements, maybe not for the others.

**Comment by mdboom** [comment]
Unless I'm misunderstanding, asv already has class level setup and teardown.  

https://asv.readthedocs.org/en/latest/writing_benchmarks.html#setup-and-teardown-functions

The difference is, of course, that the setup will still be run once per benchmark because the benchmarks are run in separate processes.

**Comment by pitrou** [comment]
> Unless I'm misunderstanding, asv already has class level setup and teardown. 

No, see the link I've posted :-)

**Comment by pv** [comment]
Without a redesign of the benchmark isolation mechanism, those seem
equivalent to the current setup/teardown routines.
.
With looser isolation, dealing with timeouts probably needs some
thought, ditto for handling crashes, and considering the effect on
reproducibility for the different benchmark types. It's probably doable
but doesn't seem completely straightforward.

**Comment by mdboom** [comment]
@pitrou: Looking at the link it's still not clear what the functional difference is between that and what asv already has implemented. Is the important difference for you that it's a classmethod rather than an instancemethod?  In the case of asv the difference would be primarily syntactic, but it would be easy enough to make classmethods work.  Or is the issue for you that it would get run once per benchmark?  Given the issues with trying to not run it more than once that @pv outlined, the cost/benefit on that may not make sense.

**Comment by pitrou** [comment]
> Looking at the link it's still not clear what the functional difference is between that and what asv already has implemented.

- setup / tearDown: called once per test *method*
- setupClass / tearDownClass: called once per test *class* (regardless of the number of test methods defined in it)

It's quite useful when you have shared resources for all tests in a class, and setting them up is costly enough that you don't want to do it again for each test method.

(substitute "benchmark" for "test" above for asv)

**Comment by mdboom** [comment]
Ok.  I get that -- but running the setup once per class doesn't really fit the model of asv.  For all the reasons @pv mentioned, implementing that is not going to be straightforward.  You can at least, as it stands now, reduce the code duplication, but not the runtime duplication due to the way the benchmarks are sandboxed.

One possible solution may be to run-and-pickle the results of the class setup methods once, and then unpickle them in each benchmark process.  If you pickled on a per-environment basis the usual marks against pickle wouldn't apply (that they are non-portable etc.)

**Comment by pitrou** [comment]
Yes, it sounds like this request isn't very promising right now. I wasn't aware of the one-process-per-benchmark model when I posted this issue (that explains while running the benchmarks feels a little slow, then :-)).

**Comment by mdboom** [comment]
@pitrou: Would you mind commenting on #277, which addresses this (hopefully) though in a slightly different way given the execution model of asv etc.
