### ISSUE TITLE
Exit status of `asv run` always 0?

### ISSUE THREAD

**Issue by bjodah** [spacetelescope/asv#296]
Is the exit status of a call to `asv run` always 0?
If there are failed tests one could argue it should exit with exit status 1.

I would find this useful in test suites run on CI servers for benchmark suites (sanity check that a proposed benchmark actually works for current master branch of benchmarked project).

**Comment by mdboom** [comment]
Hmmm...  Failing benchmarks are sort of "expected behavior" in a lot of cases, particularly for benchmarks that exercise new behavior that may not exist in the earlier history of a project.  I would expect success to be "I tried everything, and was able to save the results to disk", rather than "I tried everything and it all ran flawlessly".  Importantly, I wouldn't want a cron job to let me know when a benchmark had failed, as long as it was able to successfully collect results.

However, I wouldn't be opposed to a commandline flag for this (or some other solution that allows for both use cases).

**Comment by bjodah** [comment]
Thank you, good to know. Slightly related to this: I thought I should ask:

We have just added asv to SymPy (https://github.com/sympy/sympy_benchmarks). One thing I have been trying to figure out is if there is a way to validate the output of a timed computation so it may be exluded. A silly example:

```
class TimeSolve:
    def setup(self):
        self.x = Symbol(x)

    def time_solve(self):
        result = solve(self.x-4, self.x)
        assert result == 4
```

Often the time of computation of that last assert may be non-negligible. Is there a way to check for it "outside" the timed function? i.e. something along these lines:


```
class TimeSolve:
    def setup(self):
        self.x = Symbol(x)

    def time_solve(self):
        return solve(self.x-4, self.x)

    def test_time_solve(self, result)
        assert result == 4
```

where a failed test_time_solve() would mark the test as failed rather than including potentially very "performant" errornous results in the benchmark plots..

**Comment by pv** [comment]
You can in principle store the computed value in `self.value` and do the verification in the teardown function, raising an error if it's incorrect.

**Comment by bjodah** [comment]
@pv thank you for the pointer, I followed your advice in https://github.com/sympy/sympy_benchmarks/pull/19
