### ISSUE TITLE
Consider all class attributes in creating a benchmark

### ISSUE THREAD

**Issue by kawochen** [spacetelescope/asv#323]
CMIIW, right now a test class is just a container for the relevant functions (e.g. `setup`) and attributes.  Those are looked for specifically when creating a `benchmark` object.  When I first used `asv` to benchmark functions that would perturb the state of the input, my first instinct was to define some class attributes to allocate memory (big big arrays) and use `setup` to reset the state prior to each call.  Following #316, the `setup` part can be called repeatedly, but of course the self defined attributes still won't be retrieved. 

Is it feasible to actually create, for example, a `test_abc` _object_ in `benchmark` and access the required functions through that object.  If `setup` does access some custom class attributes, it will work.   I suppose a workaround is to use the first `setup` call to initialize inputs, and subsequent calls to reset states, but I think that is less intuitive.  Another benefit of using the whole class is that you have more flexibility in using decorators (that require complex, expensive-to-construct arguments) in defining test functions. 

Would love to learn about the reasons behind the design.

**Comment by pv** [comment]
I'm not sure I understand your point --- if you can add an example of how you would like it to work, that could be useful.

If you are asking whether an instance of the class is created for the benchmark --- yes it is, as usual (`__init__` gets called etc.).

**Comment by mdboom** [comment]
Just to add to @pv's comment: Though the class is instantiated (and `__init__` is called) when the benchmark is *run*, it is not instantiated for *discovery*.  This is an important distinction, since discovery happens in a separate process (and possibly even a different version of Python) than the benchmarks are run in.  Doing otherwise would mean that different configurations (instances of the configuration matrix) may have different benchmarks in them, which would make everything from the database to the GUI much more complex.

**Comment by kawochen** [comment]
Thanks.  I will try to go through more code to see what the discovery process does.

For my point about decorators: I was trying to make something like this work.
```
class A(object):
    number = 1
    repeat = 10
    a = 123456
    
    @test_decorator(a) # test_decorator just prints a before calling the function
    def test_something(self):
        pass
```
Now that it's confirmed that an instance is created, I'm not seeing why this would not work.  I will test this later and report back.

**Comment by pv** [comment]
@mdboom: `benchmark.py` does create an instance also on discovery. Some Scipy benchmarks already use this to set per-function attributes inside classes (could maybe be done also with decorators)...

The second thing is that it probably should not dump all class attributes into the resulting json, only those asv knows about.

**Comment by mdboom** [comment]
Sorry -- I realize I wasn't clear.  Benchmark discovery uses the class' dictionary to see what's available (though it does ultimately instantiate the class to get the attributes of the method).  I meant that only to show that any methods dynamically added to an instance wouldn't show up.  But that turned out to be irrelevant to @kawochen's question anyway...

**Comment by pv** [comment]
No further info, so closing.
