### ISSUE TITLE
Set timeout on check_output during setup of virtualenvs

### ISSUE THREAD

**Issue by thpfaff** [spacetelescope/asv#356]
The build process of our package takes longer than the default timeout of 600 seconds defined in asv.util.check_output and thus asv fails on building the virtual environment.

Is there a way to change this by configuration?

**Comment by pv** [comment]
To pinpoint the issue a bit more closely: the timeout is 10 minutes
without output, which should be usually sensible.
.
However, if the issue occurs in setting up the virtual environment, then
it may be due to pip swallowing the build output --- if this is the
issue, a better fix would be for the virtualenv plugin to call `pip
install -v`.

**Comment by thpfaff** [comment]
Adding -v to the install command works.
However, it finishes much earlier than 10 minutes.
I checked back and the original timeout also occurs much earlier than 10 minutes.
Apparently, `select.select` returns before the timeout but with an empty `rlist`. Not sure, how this is possible.

**Comment by pv** [comment]
The timeout used to be 2 min in asv 0.1.1, but if that's not the explanation then I don't know how select can return early.

**Comment by thpfaff** [comment]
Yes, the timeout happens roughly after 2 minutes.
I'm using pip's environment variable precedence for the time being. Setting `export PIP_VERBOSE=1` makes things work again.

Thanks for your help.
