### ISSUE TITLE
Implement a notification system

### ISSUE THREAD

**Issue by philpep** [spacetelescope/asv#397]
One possible implementation could be to generate a rss/atom feed of regressions in the static website. What do you think ?

**Comment by mdboom** [comment]
I think that's a great idea!

**Comment by philpep** [comment]
The hard part is what date using as "publication date" in the feed item ? This date must be stable along rebuild of the static website (asv publish).

Here are possibles candidates/solutions:

  * Commit "author date" (``%ad`` in git log format). I'm not in flavor of this cf #390
  * Commit "commit date" (``%cd`` in git log format). No equivalent in mercurial.
  * Benchmark build date cf #400  
  * When publishing, it the target ``regressions.json`` and future ``regressions.xml`` exists, make a diff of regressions and eventually add new items in the feed (instead of overriding). IMHO it's a bit magic, but sould work pretty well.

**Comment by pv** [comment]
I would prefer to keep the html output as write-only, so that you can always throw the old html away.

The benchmark build date is probably the one most closely related to the date when the regression was actually detected. One thing here is that due to the noise in the results, it will lag a few benchmark runs behind, so you get new publications in the past. However, the order of publications is the same as if the publication date was the date of actual publication, so this sounds good to me.

**Comment by pv** [comment]
Initial stab at this: https://github.com/spacetelescope/asv/compare/master...pv:regressions-feed

**Comment by philpep** [comment]
@pv thanks ! I was planning to work on it (but didn't yet). I'll try this on top of #429

**Comment by pv** [comment]
Great, feel free to take over! It doesn't currently organize the feed in 
the same way as the web page, I run out of time yesterday...

**Comment by pv** [comment]
Implemented in #447

**Comment by philpep** [comment]
@pv looks perfect ! Thanks !
