### ISSUE TITLE
asv html site not working correctly

### ISSUE THREAD

**Issue by astrofrog** [spacetelescope/asv#438]
I am having issues previewing the HTML results site for the following example repo:

https://github.com/astrofrog/asv-debug

If I clone this, then do:

```
asv publish
asv preview
```

then click on one of the preview graphs that appears, the resulting pages are very slow and show either no results or only some of them.

**Comment by pv** [comment]
The problem is in how `graphdisplay.js` deals with environment parameter permutations.

In particular, on graphdisplay.js:779, `var state_permutations = permutations(state);` generates 16200 combinations --- of which only 5 are valid. Since the valid combinations are known at `asv publish` stage, this part needs to be rewritten so that `index.json` contains a list of available combinations, and the list is filtered based on `state` in `graphdisplay.js:replace_graphs.collect_graphs`.

Permutation generation is OK for parameterized benchmarks, since for those all combinations are anyway generated, but not for the machine parameters where the result set can be much sparser.

**Comment by pv** [comment]
iow, not a new bug afaics, but requires just running on more environment combinations than what anyone seems to have tested before this

**Comment by astrofrog** [comment]
@pv - ok, thanks for clarifying this! Just for info, I'm also running into this for another benchmark repo where I've added a second set of results - I think because all the version numbers for dependencies differ, the number of permutations is again very large.

**Comment by pv** [comment]
fix in #440
