### ISSUE TITLE
Measure statistics of benchmark results

### ISSUE THREAD

**Issue by pv** [spacetelescope/asv#486]
Currently, timing benchmarks numbers come from `min(timeit.repeat(number, repeat))/number`. A more statistically aware approach is probably necessary, because `asv compare` and `asv continuous` need to compare these numbers. This is not as important for the continuous regression detection, which currently infers the statistics from the historical data --- however, having the extra information may be useful if the number of commits benchmarked is small.

The results JSON files should store not only the single aggregate number, but also some empirical confidence interval / quantiles or some other metric of the spread in the results.

If we are not storing all the samples, I think `benchmark.py` should use some estimator to give a single number as a result (e.g. the mean) as it does now, and the additional information should characterize the distribution of this estimator. Then the rest of `asv` could make judgments on whether two results differ, based on these distributions. It's probably best to not do very fancy statistics here, because I think often the number of samples will be small, so the results will give little information on how the distributions look in detail. 

A complication for timing benchmarks is eliminating the benchmarking overhead.
An approach based on linear-regression on `(num_iter, total_time)` has been used e.g. in 
https://blogs.janestreet.com/core_bench-micro-benchmarking-for-ocaml/ and elsewhere.

I think a weakness of this approach is that the results of subsequent iterations can be correlated (see `bench_linalg.Eindot.time_einsum_ij_jk_a_b` in Numpy benchmarks) --- e.g., first round for `num_iter = 1, 2, 4, 8, ...` gives one set of results, and when re-run, some uncontrolled variable changes (e.g. CPU cache miss) and gives results with a different offset. Now, the regression will have trouble in figuring out the slope, even if both rounds only differ in the offset. A question now is whether the correct behavior is to accept this and report the number and the very big spread, or try to force some assumptions (e.g. just discard outliers), or whether reporting the slope is sensible?

Some work here (currently works, but has the weakness from the linear regression approach): https://github.com/spacetelescope/asv/compare/master...pv:timing-estimator2

**Comment by njsmith** [comment]
@haypo has been doing a ton of careful work on figuring out how to do statistically reliable benchmarking in Python -- in particular with his whole [perf package](https://perf.readthedocs.io/en/latest/). It might make sense to outsource the core measuring part to `perf`, and let `asv` focus on the logistics of results management / graphing / etc.? Or even if not then I'm guessing you and @haypo have a lot to talk about :-).

**Comment by njsmith** [comment]
(I just found this bug because I was trying to use asv to compare two specific commits, and getting frustrated because in my case asv's results are way too noisy to just eyeball, and there's no stats. perf OTOH gives useful stats but it's a lot of work to get it to run my benchmarks against different versions of my project. So I came here to suggest working together and lo, the first issue in the list was exactly on topic...)

**Comment by pv** [comment]
Yes, I've read @haypo's work, and found it very informative.
.
I think most important part of this is getting the statistical approach 
"right" in the sense that it's sensible for the type of data at hand 
(noisy, not necessarily many samples, not normal distributed). I'm not 
sure it's possible to "factor it out" of asv, since it needs to work its 
way into the compare and step detection routines.
.
(The specific issue of correlated samples in linear regression above can 
probably be eliminated just by subtracting the N=1 measurement.)

**Comment by haypo** [comment]
"_Currently, timing benchmarks numbers come from min(timeit.repeat(number, repeat))/number._"

Please stop using min() right now :-) http://perf.readthedocs.io/en/latest/perf.html#minimum-versus-average-and-standard-deviation


"_A more statistically aware approach is probably necessary, because asv compare and asv continuous need to compare these numbers. This is not as important for the continuous regression detection, which currently infers the statistics from the historical data --- however, having the extra information may be useful if the number of commits benchmarked is small._"

My perf module stores all timings, even warmup samples, in JSON files. It recomputes statistics on demand. I know that some people prefer to only store the result like average, std dev, min, etc. in JSON, but there are are reasons to store everything. To compare two benchmark results, the "perf compare" command checks if the comparison is significant, and you need all samples to compute that. Moreover, perf has utilities like "perf hist" to render an histogram and "perf dump" to dump all timings.


"_If we are not storing all the samples, I think benchmark.py should use some estimator to give a single number as a result (e.g. the mean) as it does now, and the additional information should characterize the distribution of this estimator._"

Please provide also the standard deviation, it's a very important information.


"_Then the rest of asv could make judgments on whether two results differ, based on these distributions. It's probably best to not do very fancy statistics here, because I think often the number of samples will be small, so the results will give little information on how the distributions look in detail._"

I would like to check if a benchmark result is bimodal, but I don't know how to implement that and it was not my priority:
https://en.wikipedia.org/wiki/Multimodal_distribution

Again, you need all samples to compute that.

"_A complication for timing benchmarks is eliminating the benchmarking overhead.
An approach based on linear-regression on (num_iter, total_time) has been used e.g. in
https://blogs.janestreet.com/core_bench-micro-benchmarking-for-ocaml/ and elsewhere._"

The pybench tool duplicated each benchmark: one flavor with an empty "pass" loop body, one flavor with the real code. It uses min() to get the minimum duration of the "pass" flavor and substruct it from the "real code" flavor.

The problem is that you simply cannot summarize a benchmark using min(). There is no reliable way to measure the "overhead" of a benchmark. They are just too many parameters impacting benchmarks, especially if one inner loop iteration of your benchmark takes less than 1 us. Take a look at my blog for real world issues with complex low-level features of mordern Intel CPUs:
http://haypo.github.io/

It's also very complex (or impossible? :-)) to run a benchmark on a Python implementation using a JIT compiler like PyPy:
http://perf.readthedocs.io/en/latest/perf.html#jit-compilers

I suggest you to forget your idea of computing the benchmark overhead, and focus on reducing the overhead :-) In my perf API, I provide a bench_sample_func() method: you have to pass a function which returns the timing, so the user of the API can optimize the benchmark to reduce the overhead:
http://perf.readthedocs.io/en/latest/api.html#Runner.bench_sample_func

Example:

```
def bench_calls(loops):
    range_it = xrange(loops)
    t0 = perf.perf_counter()

    for loops in range_it:
        # 20 calls
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)
        foo(1, 2, 3, 4)

    return perf.perf_counter() - t0


if __name__ == "__main__":
    runner = perf.Runner()
    runner.metadata['description'] = ("Test the performance of simple "
                                      "Python-to-Python function calls")
    runner.bench_sample_func('call_simple', bench_calls, inner_loops=20)
```

This benchmark manually duplicates the loop body 20 times to reduce the overhead of the outer loop. It also creates the range() object out of the benchmark.

Note: The perf module automatically computes the number of outer loops (loops parameter of bench_calls) for you using a non-obvious calibration algorithm.

**Comment by pv** [comment]
Thanks for the comment, I'm agreeing with what you write. Using the 
minimum of averages is I guess from the initial version of asv, and 
probably came directly from timeit.
.
It's true that by not trying to subtract the benchmark overhead, the 
statistical analysis becomes much simpler. However, I think this is not 
something impossible to do in principle.

**Comment by haypo** [comment]
I didn't know asv. It seems to contain advanced statistics functions and a nice UI.

I suggest to you to keep all your code to analyze and browse benchmark results (UI), but use the perf module to *run* the benchmark.

According to your API, it shouldn't be hard to use perf to run existing asv benchmarks.

**Comment by pv** [comment]
gh-493
