### ISSUE TITLE
Build project with make

### ISSUE THREAD

**Issue by rconan** [spacetelescope/asv#520]
Hi,

how can I get asv to run `make` on my project before running the benchmarks?

Thanks
Rod

**Comment by pv** [comment]
Only Python packages installable by pip are supported.

**Comment by pv** [comment]
Only Python packages installable by pip are supported currently.

**Comment by tylerjereddy** [comment]
@pv Does this include Python packages that are installable by pip, but have `setup.py` in a non-standard location? For example, I work on one package that is available on PyPI / can be pip installed, but has `setup.py` in a subdirectory instead of the package root.

It is not immediately clear to me how one specifies a non-standard `setup.py` path, and indeed the blue box in the [asv docs](http://asv.readthedocs.io/en/latest/using.html) may suggest that this isn't currently possible?

If this isn't currently supported, would it be difficult to add this functionality? I could try to work on it with some guidance, but only if that's something of interest to the devs.

**Comment by pv** [comment]
The constraint is mainly that the package should be cleanly
uninstallable from virtualenv, which probably becomes complicated
without pip.
.
However, Python code in a subdirectory probably of a repository is
probably fine in this respect.

**Comment by pv** [comment]
The issue itself is dup of #78
